<<<<<<< HEAD
angular.module("evaluon.templates", []).run(["$templateCache", function($templateCache) {$templateCache.put("views/auth/login.tpl.html","<div layout=\"horizontal\" layout-padding layout-align=\"center\" >\n    <div flex=\"30\">\n        <md-toolbar class=\"md-whiteframe-z3\">\n            <div class=\"md-toolbar-tools\">\n                <span>Evaluon</span>\n                <span flex>Login</span>\n            </div>\n        </md-toolbar>\n        <md-content class=\"md-padding md-whiteframe-z5\" md-theme=\"light-blue-dark\" layout-padding layout-align=\"center\">\n            <form layout=\"vertical\" layout-align=\"center center\" ng-submit=\"login($event)\">\n                <md-text-float label=\"Correo\" type=\"email\" ng-model=\"user.email\" ng-required=\"true\"> </md-text-float>\n                <md-text-float label=\"Contraseña\" type=\"password\" ng-model=\"user.password\" ng-required=\"true\"> </md-text-float>\n                <md-button type=\"submit\" aria-label=\"Iniciar Sesion\" md-theme=\"light-blue-dark\" class=\"md-primary\">\n                    Iniciar Sesion\n                </md-button>\n            </form>\n        </md-content>\n    </div>\n</div>\n");
$templateCache.put("views/entity/home.tpl.html","");
$templateCache.put("views/evaluator/home.tpl.html","");
$templateCache.put("views/institution/home.tpl.html","");
$templateCache.put("views/errors/404.tpl.html","<div layout=\"horizontal\" layout-padding layout-align=\"center\" >\n    <div flex=\"30\">\n        <md-toolbar class=\"md-whiteframe-z1\">\n            <div class=\"md-toolbar-tools\">\n                <span>Evaluon</span>\n            </div>\n        </md-toolbar>\n        <md-content class=\"md-padding md-whiteframe-z3\" layout-padding layout-align=\"center\">\n            <h1 layout=\"vertical\" layout-padding layout-align=\"center center\">404</h1>\n        </md-content>\n    </div>\n</div>\n");}]);
=======
angular.module("evaluon.templates", []).run(["$templateCache", function($templateCache) {$templateCache.put("views/auth/login.tpl.html","<div layout=\"horizontal\" layout-padding layout-align=\"center\" >\n  <div flex=\"30\">\n    <md-toolbar class=\"md-whiteframe-z3\">\n      <div class=\"md-toolbar-tools\">\n        <span>Evaluon</span>\n        <span flex>Login</span>\n      </div>\n    </md-toolbar>\n    <md-content class=\"md-padding md-whiteframe-z5\" md-theme=\"light-blue-dark\" layout-padding layout-align=\"center\">\n      <form layout=\"vertical\" layout-align=\"center center\" ng-submit=\"login($event)\">\n        <md-text-float label=\"Correo\" type=\"email\" ng-model=\"user.email\" ng-required=\"true\"> </md-text-float>\n        <md-text-float label=\"Contraseña\" type=\"password\" ng-model=\"user.password\" ng-required=\"true\"> </md-text-float>\n        <md-button type=\"submit\" aria-label=\"Iniciar Sesion\" md-theme=\"light-blue-dark\" class=\"md-primary\">\n           Iniciar Sesion\n        </md-button>\n      </form>\n   </md-content>\n  </div>\n</div>\n");
$templateCache.put("views/entity/entity.tpl.html","<div layout=\"horizontal\" flex>\n    <md-sidenav class=\"md-sidenav-left md-whiteframe-z2\" component-id=\"left\" is-locked-open=\"$media(\'md\')\"  layout=\"vertical\">\n       <md-toolbar>\n         <h1 class=\"md-toolbar-tools\">INCI</h1>\n       </md-toolbar>\n       <md-content flex layout=\"vertical\" class=\"md-default-theme\" style=\"height: 700px;\">\n         <md-button>\n           Instituciones\n         </md-button>\n       </md-content>\n    </md-sidenav>\n  <div layout=\"vertical\" layout-fill>\n    <md-toolbar>\n       <div class=\"md-toolbar-tools\">\n        <span>Evaluon</span>\n        <span flex>Login</span>\n       </div>\n    </md-toolbar>\n    <md-content ui-view>\n\n    </md-content>\n  </div>\n</div>\n");
$templateCache.put("views/entity/home.tpl.html","");
$templateCache.put("views/evaluator/evaluator.tpl.html","");
$templateCache.put("views/evaluator/home.tpl.html","");
$templateCache.put("views/institution/home.tpl.html","");
$templateCache.put("views/institution/institution.tpl.html","");}]);
>>>>>>> feature-homes
